name: Build and Dockerize Full Stack App

on:
  push:
    branches: [ "main" ]

jobs:
  #backend:
    #name: Build Backend & Docker Image
    #runs-on: ubuntu-latest

    #steps:
      #- name: Checkout code
        #uses: actions/checkout@v4

      #- name: Set up Java
        #uses: actions/setup-java@v4
        #with:
          #distribution: temurin
          #java-version: 17

      #- name: Cache Maven dependencies
       # uses: actions/cache@v4
       # with:
          #path: ~/.m2
          #key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          #restore-keys: |
            #${{ runner.os }}-maven-

      #- name: Build Spring Boot JAR
        #working-directory: backend
        #run: mvn clean package -DskipTests

      #- name: Set up Docker
        #uses: docker/setup-buildx-action@v3

      #- name: Build backend Docker image
        #run: |
          #docker build -t backend-app:new1 ./backend
          #docker images 

  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install frontend dependencies
        working-directory: ./
        run: |
          echo "All files and folders and path before build"
          pwd
          ls -ltr
          sleep 10
          npm install

      - name: Build Angular app
        working-directory: ./
        run: |
          npm run build -- --configuration=production
          sleep 10
          echo "All files and folders and path after build"
          pwd
          ls -ltr

      #- name: Set up Docker
        #uses: docker/setup-buildx-action@v3

      #- name: Build frontend Docker image
        #run: |
          #docker build -t frontend-app:new1 ./frontend
          #docker images
